"""empty message

Revision ID: ea6504dba505
Revises: dccdc758a48a
Create Date: 2018-09-18 09:58:04.990643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6504dba505'
down_revision = 'dccdc758a48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_buser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('consumer_key', sa.String(length=64), nullable=True),
    sa.Column('consumer_key_secret', sa.String(length=64), nullable=True),
    sa.Column('data_table', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_d_buser_account_id'), 'd_buser', ['account_id'], unique=True)
    op.create_index(op.f('ix_d_buser_campaign_id'), 'd_buser', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_d_buser_consumer_key'), 'd_buser', ['consumer_key'], unique=True)
    op.create_index(op.f('ix_d_buser_consumer_key_secret'), 'd_buser', ['consumer_key_secret'], unique=True)
    op.create_index(op.f('ix_d_buser_data_table'), 'd_buser', ['data_table'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_d_buser_data_table'), table_name='d_buser')
    op.drop_index(op.f('ix_d_buser_consumer_key_secret'), table_name='d_buser')
    op.drop_index(op.f('ix_d_buser_consumer_key'), table_name='d_buser')
    op.drop_index(op.f('ix_d_buser_campaign_id'), table_name='d_buser')
    op.drop_index(op.f('ix_d_buser_account_id'), table_name='d_buser')
    op.drop_table('d_buser')
    # ### end Alembic commands ###
